### ISSUE TITLE
[FEAT] Add Vite.js support

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/studio#109]
#### Describe the feature
We need to support Vite to enable other framework support such as Remix and Astro. Might only require testing and updating the docs for the babel plugin. 

Should work similar to this: https://docs.mightymeld.com/docs/setup/plugin/vite-babel

Optional: Add a Vite project to demos folder with working config.

**Comment by bkrmendy** [comment]
I started looking into this independently already. I came the same conclusion that @Kiet outlines in the issue, creating a full-blown Vite plugin would be overkill for now (because it would just wrap the babel plugin, and there's already a generic babel plugin for Vite, so the onlook babel plugin and the Vite babel plugin could be composed together).

**Comment by bkrmendy** [comment]
PR: https://github.com/onlook-dev/studio/pull/122
